CREATE TABLE IF NOT EXISTS STATUS
(
  STATUS_CODE       VARCHAR2 (10) NOT NULL PRIMARY KEY ,
  STATUS_DEFINITION VARCHAR2 (200)
);

CREATE TABLE IF NOT EXISTS CAMT055_XML
(
  MESSAGE_ID   VARCHAR2 (35) NOT NULL PRIMARY KEY ,
  XML_DATA     CLOB ,
  CREATED_DATE DATE ,
  STATUS_CODE VARCHAR2 (10) NOT NULL
);

CREATE INDEX IF NOT EXISTS CAMT055_XML_STATUS_FK_IDX ON CAMT055_XML
(
  STATUS_CODE ASC
);
ALTER TABLE CAMT055_XML ADD CONSTRAINT IF NOT EXISTS CAMT055_XML_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

CREATE TABLE IF NOT EXISTS PAIN002_CAMT055_XML
(
  PAIN002_CAMT055_XML_ID   VARCHAR2 (35) NOT NULL PRIMARY KEY ,
  CAMT055_MESSAGE_ID VARCHAR2(35) ,
  SENT_DATE DATE ,
  STATUS_CODE VARCHAR2 (10) NOT NULL,
  XML_DATA    CLOB
);

CREATE INDEX IF NOT EXISTS PAINCAMT_XML_FK_IDX ON PAIN002_CAMT055_XML
(
  STATUS_CODE ASC
);

ALTER TABLE PAIN002_CAMT055_XML ADD CONSTRAINT IF NOT EXISTS PAINCAMT_XML_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;
ALTER TABLE PAIN002_CAMT055_XML ADD CONSTRAINT IF NOT EXISTS PAIN002_CAMT055_FK FOREIGN KEY ( CAMT055_MESSAGE_ID ) REFERENCES CAMT055_XML ( MESSAGE_ID ) NOT DEFERRABLE ;

CREATE TABLE IF NOT EXISTS CAMT029_XML
(
  CAMT029_XML_ID VARCHAR2 (35) NOT NULL PRIMARY KEY ,
  CAMT055_MESSAGE_ID  VARCHAR2 (35) NOT NULL,
  CREATED_DATE   DATE ,
  STATUS_CODE    VARCHAR2 (10) NOT NULL ,
  XML_DATA       CLOB
);

CREATE INDEX IF NOT EXISTS CAMT029_XML_STATUS_FK_IDX ON CAMT029_XML
(
  STATUS_CODE ASC
);

ALTER TABLE CAMT029_XML ADD CONSTRAINT IF NOT EXISTS CAMT029_XML_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;
ALTER TABLE CAMT029_XML ADD CONSTRAINT IF NOT EXISTS CAMT029_CAMT055_FK FOREIGN KEY ( CAMT055_MESSAGE_ID ) REFERENCES CAMT055_XML ( MESSAGE_ID ) NOT DEFERRABLE ;

CREATE SEQUENCE IF NOT EXISTS SEQ_CAMT054_XML_ID START WITH 1 ;

CREATE TABLE IF NOT EXISTS CAMT054_XML
  (
    CAMT054_XML_ID NUMBER (10) DEFAULT SEQ_CAMT054_XML_ID.NEXTVAL IDENTITY NOT NULL PRIMARY KEY ,
    XML_DATA       CLOB ,
    PAYMENT_DATE   DATE ,
    STATUS_CODE    VARCHAR2 (10) NOT NULL
  );

CREATE INDEX IF NOT EXISTS CAMT054_XML_STATUS_FK_IDX ON CAMT054_XML
  (
    STATUS_CODE ASC
  );
  
--ALTER TABLE CAMT054_XML ADD CONSTRAINT IF NOT EXISTS CAMT054_XML_PK PRIMARY KEY ( CAMT054_XML_ID );

CREATE TABLE IF NOT EXISTS PAIN001_XML
(
  MESSAGE_ID     VARCHAR2 (35) NOT NULL PRIMARY KEY,
  XML_DATA       CLOB,
  STATUS_CODE    VARCHAR2 (10) NOT NULL,
  CREATED_DATE   DATE
);

--ALTER TABLE PAIN001_XML ADD CONSTRAINT IF NOT EXISTS PAIN001_XML_PK PRIMARY KEY ( MESSAGE_ID ); ;

CREATE TABLE IF NOT EXISTS PAIN002_XML
  (
  	PAIN002_XML_ID  VARCHAR2 (200) NOT NULL PRIMARY KEY ,
    MESSAGE_ID  VARCHAR2 (35) NOT NULL ,
    XML_DATA    CLOB ,
    SENT_DATE   DATE ,
    STATUS_CODE VARCHAR2 (10) NOT NULL
  );

CREATE INDEX IF NOT EXISTS PAIN002_XML_STATUS_FK_IDX ON PAIN002_XML
  (
    STATUS_CODE ASC
  );
  
--ALTER TABLE PAIN002_XML ADD CONSTRAINT IF NOT EXISTS PAIN002_XML_PK PRIMARY KEY ( PAIN002_XML_ID );

CREATE TABLE IF NOT EXISTS PAYMENT_MESSAGE
  (
    MESSAGE_ID             VARCHAR2 (35) NOT NULL PRIMARY KEY REFERENCES PAIN001_XML(MESSAGE_ID) ,
    PAIN001_XML_ID         NUMBER (8) NOT NULL,
    CREATED_DATE           DATE ,
    NUMBER_OF_TRANSACTIONS NUMBER (8) ,
    TRANSACTION_SUM        NUMBER (19,2) ,
    BIC                    VARCHAR2 (50) ,
    MESSAGE_NAME           VARCHAR2 (50) ,
    STATUS_CODE            VARCHAR2 (10) NOT NULL
  );
  
CREATE INDEX IF NOT EXISTS PMT_MSG_STATUS_FK_IDX ON PAYMENT_MESSAGE
  (
    STATUS_CODE ASC
  );
  
--ALTER TABLE PAYMENT_MESSAGE ADD CONSTRAINT IF NOT EXISTS PMT_MSG_PK PRIMARY KEY ( MESSAGE_ID );

CREATE TABLE IF NOT EXISTS PAYMENT_INFORMATION
  (
    PAYMENT_INFORMATION_ID VARCHAR2 (35) NOT NULL PRIMARY KEY ,
    MESSAGE_ID             VARCHAR2 (35) NOT NULL ,
    DUE_DATE               DATE ,
    NUMBER_OF_TRANSACTIONS NUMBER (8) ,
    TRANSACTIONS_SUM       NUMBER (19,2) ,
    DEBITOR_ACCOUNT_NUMBER VARCHAR2 (35) ,
    STATUS_CODE            VARCHAR2 (10) NOT NULL
  );
  
CREATE INDEX IF NOT EXISTS PMT_INFO_PMT_MSG_FK_IDX ON PAYMENT_INFORMATION
  (
    MESSAGE_ID ASC
  );
  
CREATE INDEX IF NOT EXISTS PMT_INFO_STATUS_FK_IDX ON PAYMENT_INFORMATION
  (
    STATUS_CODE ASC
  );
  
--ALTER TABLE PAYMENT_INFORMATION ADD CONSTRAINT IF NOT EXISTS PMT_INFO_PK PRIMARY KEY ( PAYMENT_INFORMATION_ID );

CREATE TABLE IF NOT EXISTS PAYMENT_TRANSACTION
  (
    TRANSACTION_ID         VARCHAR2 (35) NOT NULL PRIMARY KEY ,
    END_TO_END_ID          VARCHAR2 (35) NOT NULL,
    ACCOUNT_NUMBER         VARCHAR2 (35) ,
    NAME                   VARCHAR2 (50) ,
    AMOUNT                 NUMBER (19,2) ,
    CURRENCY               VARCHAR2 (10) ,
    STATUS_CODE            VARCHAR2 (10) NOT NULL ,
    PAYMENT_INFORMATION_ID VARCHAR2 (35) NOT NULL
  );
  
CREATE INDEX IF NOT EXISTS PMT_TRN_PMT_INFO_FK_IDX ON PAYMENT_TRANSACTION
  (
    PAYMENT_INFORMATION_ID ASC
  );
  
CREATE INDEX IF NOT EXISTS PMT_TRN_STATUS_FK_IDX ON PAYMENT_TRANSACTION
  (
    STATUS_CODE ASC
  );
  
--ALTER TABLE PAYMENT_TRANSACTION ADD CONSTRAINT IF NOT EXISTS PMT_TRN_PK PRIMARY KEY ( TRANSACTION_ID );

CREATE SEQUENCE IF NOT EXISTS SEQ_AVVIK_ID START WITH 1 ;

CREATE TABLE IF NOT EXISTS AVVIK
  (
    AVVIK_ID NUMBER(10) DEFAULT SEQ_AVVIK_ID.NEXTVAL IDENTITY NOT NULL PRIMARY KEY,
    TEST_ID NUMBER (10) NOT NULL,
    MELDING_ID_TEKN_AVVISNING VARCHAR2 (35),
    MELDING_ID_VAL_AVVISNING VARCHAR2 (35),
    BUNT_ID VARCHAR2 (35),
    TRANSAKSJON_ID VARCHAR2 (35),
    NAVN_MOTTAKER VARCHAR2 (35),
    KONTONR_MOTTAGER VARCHAR2 (35),
    RETURSTATUS VARCHAR2 (35),
    AVVIK_KODE VARCHAR2 (35),
    AVVIK_BESKRIVELSE VARCHAR2 (35)
  );



--ALTER TABLE STATUS ADD CONSTRAINT IF NOT EXISTS STATUS_PK PRIMARY KEY ( STATUS_CODE );

ALTER TABLE CAMT054_XML ADD CONSTRAINT IF NOT EXISTS CAMT054_XML_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

ALTER TABLE PAIN001_XML ADD CONSTRAINT PAIN001_XML_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

ALTER TABLE PAIN002_XML ADD CONSTRAINT IF NOT EXISTS PAIN002_XML_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

ALTER TABLE PAIN002_XML ADD CONSTRAINT IF NOT EXISTS PAIN002_XML_PAIN001_XML_FK FOREIGN KEY ( MESSAGE_ID ) REFERENCES PAIN001_XML ( MESSAGE_ID ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_INFORMATION ADD CONSTRAINT IF NOT EXISTS PMT_INFO_PMT_MSG_FK FOREIGN KEY ( MESSAGE_ID ) REFERENCES PAYMENT_MESSAGE ( MESSAGE_ID ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_INFORMATION ADD CONSTRAINT IF NOT EXISTS PMT_INFO_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_MESSAGE ADD CONSTRAINT IF NOT EXISTS PMT_MSG_PAIN001_XML_FK FOREIGN KEY ( MESSAGE_ID ) REFERENCES PAIN001_XML ( MESSAGE_ID ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_MESSAGE ADD CONSTRAINT IF NOT EXISTS PMT_MSG_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_TRANSACTION ADD CONSTRAINT IF NOT EXISTS PMT_TRN_PMT_INFO_FK FOREIGN KEY ( PAYMENT_INFORMATION_ID ) REFERENCES PAYMENT_INFORMATION ( PAYMENT_INFORMATION_ID ) NOT DEFERRABLE ;

ALTER TABLE PAYMENT_TRANSACTION ADD CONSTRAINT IF NOT EXISTS PMT_TRN_STATUS_FK FOREIGN KEY ( STATUS_CODE ) REFERENCES STATUS ( STATUS_CODE ) NOT DEFERRABLE ;


INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('ACTC', 'Accepted technical');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('RCVD', 'Received');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('PART', 'Partially accepted');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('RJCT', 'Rejected');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('PDNG', 'Pending');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('ACCP', 'Accepted');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('ACSP', 'Accepted settlement in process');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('ACSC', 'Accepted settlement completed');
INSERT INTO STATUS (STATUS_CODE, STATUS_DEFINITION) VALUES ('ACWC', 'Accepted with change');

CREATE SEQUENCE IF NOT EXISTS SEQ_KODEVERDI_ID START WITH 1 ;

CREATE TABLE IF NOT EXISTS KODEVERDI(
    KODEVERDI_ID  NUMBER   (10) DEFAULT SEQ_KODEVERDI_ID.NEXTVAL IDENTITY NOT NULL PRIMARY KEY,
    DOMENE        VARCHAR2 (35),
    NOKKEL        VARCHAR2 (35),
    VERDI         VARCHAR2 (200),
    BRUKERID      VARCHAR2 (35)
  );
