DROP TABLE STROMMAALINGER IF EXISTS ;
--DROP TABLE ORDER IF EXISTS ;
DROP TABLE CUSTOMER IF EXISTS ;
DROP TABLE PAIN002_CAMT055_XML IF EXISTS;
DROP TABLE CAMT055_XML IF EXISTS;
DROP TABLE CAMT054_XML IF EXISTS;
DROP TABLE CAMT029_XML IF EXISTS;
DROP TABLE PAIN001_XML IF EXISTS;
DROP TABLE PAIN002_XML IF EXISTS;
DROP TABLE PAYMENT_MESSAGE IF EXISTS;
DROP TABLE PAYMENT_INFORMATION IF EXISTS;
DROP TABLE PAYMENT_TRANSACTION IF EXISTS;
DROP TABLE STATUS IF EXISTS;
DROP TABLE AVVIK IF EXISTS;

DROP SEQUENCE SEQ_CAMT054_XML_ID IF EXISTS;
DROP SEQUENCE SEQ_PAIN002_XML_ID IF EXISTS;
DROP SEQUENCE SEQ_CAMT054_XML_ID IF EXISTS;
DROP SEQUENCE SEQ_CAMT054_XML_ID IF EXISTS;
DROP SEQUENCE SEQ_CAMT054_XML_ID IF EXISTS;


